"use client";

import {
  Activity,
  ArrowLeft,
  CheckCircle2,
  Clock,
  Cpu,
  Database,
  Flame,
  Gauge,
  Info,
  ShieldCheck,
  SunMedium,
  Thermometer,
  Wind,
} from "lucide-react";
import { useShelterConfiguration } from "@/context/ShelterConfigurationContext";

export function SimulationResults({
  onNavigateToSimulation,
}: {
  onNavigateToSimulation: () => void;
}) {
  const { simulationResult, location } = useShelterConfiguration();

  if (!simulationResult) {
    return (
      <div className="climate-page">
        <div className="page-heading">
          <div>
            <p className="eyebrow">STAGE 7 · SIMULATION RESULTS</p>
            <h1>Thermal Simulation Results</h1>
            <p className="page-description">
              Analysis results generated by the server simulation engine.
            </p>
          </div>
        </div>

        <div className="panel" style={{ padding: "40px 24px", textAlign: "center" }}>
          <div className="empty-icon" style={{ margin: "0 auto 16px" }}>
            <Activity aria-hidden />
          </div>
          <h3>No Simulation Results Available</h3>
          <p style={{ maxWidth: "440px", margin: "0 auto 20px", color: "#68808f", fontSize: "12px" }}>
            Run the 24-hour transient thermal simulation to view thermal comfort ratings, peak HVAC plant sizing, and energy breakdowns.
          </p>
          <button
            type="button"
            className="primary-button"
            onClick={onNavigateToSimulation}
            style={{ margin: "0 auto" }}
          >
            <ArrowLeft aria-hidden />
            Go to Simulation Setup
          </button>
        </div>
      </div>
    );
  }

  const { comfort, hvac_summary, steady_state, capacitance_j_per_k, mode, climate_source_label } =
    simulationResult;

  return (
    <div className="climate-page">
      {/* Page Heading */}
      <div className="page-heading climate-heading">
        <div>
          <p className="eyebrow">STAGE 7 · SIMULATION RESULTS</p>
          <h1>Thermal Simulation Results</h1>
          <p className="page-description">
            Simulation complete. Summary of 24-hour transient results computed by the backend.
          </p>
        </div>
        <div className="configured-pill">
          <span className="status-dot status-dot-configured" />
          Simulation Complete
        </div>
      </div>

      {/* Top Banner */}
      <div className="geometry-success-banner" style={{ marginBottom: "20px" }}>
        <CheckCircle2 aria-hidden />
        <span>
          24-hour transient calculation completed successfully for{" "}
          <strong>{location?.preset?.name ?? "Configured Site"}</strong>. Data source:{" "}
          <strong>{climate_source_label}</strong>.
        </span>
      </div>

      {/* 3 Key Metric Cards */}
      <div className="results-kpi-grid">
        {/* KPI 1: Comfort Percentage */}
        <div className="results-kpi-card">
          <div className="kpi-icon-wrap" style={{ background: "#edf7f0", color: "#2e7a50" }}>
            <Thermometer aria-hidden />
          </div>
          <div className="kpi-info">
            <span className="kpi-label">Thermal Comfort</span>
            <strong className="kpi-value" style={{ color: "#2e7a50" }}>
              {comfort.comfort_pct.toFixed(1)}%
            </strong>
            <span className="kpi-sub">
              {comfort.hours_in_band} of {comfort.total_hours} hours in comfort band ({comfort.t_low_c} – {comfort.t_high_c} °C)
            </span>
          </div>
        </div>

        {/* KPI 2: Peak Heating Load */}
        <div className="results-kpi-card">
          <div className="kpi-icon-wrap" style={{ background: "#fff5ed", color: "#d96b27" }}>
            <Flame aria-hidden />
          </div>
          <div className="kpi-info">
            <span className="kpi-label">Peak Heating Demand</span>
            <strong className="kpi-value" style={{ color: "#d96b27" }}>
              {hvac_summary.peak_heating_w > 0
                ? `${hvac_summary.peak_heating_w.toFixed(0)} W`
                : "0 W"}
            </strong>
            <span className="kpi-sub">
              {mode === "setpoint" ? "Active heating holding load" : "Passive mode (0 W HVAC)"}
            </span>
          </div>
        </div>

        {/* KPI 3: Peak Cooling Load */}
        <div className="results-kpi-card">
          <div className="kpi-icon-wrap" style={{ background: "#eef6fc", color: "#216f9d" }}>
            <Gauge aria-hidden />
          </div>
          <div className="kpi-info">
            <span className="kpi-label">Peak Cooling Demand</span>
            <strong className="kpi-value" style={{ color: "#216f9d" }}>
              {hvac_summary.peak_cooling_w > 0
                ? `${hvac_summary.peak_cooling_w.toFixed(0)} W`
                : "0 W"}
            </strong>
            <span className="kpi-sub">
              {mode === "setpoint" ? "Active cooling holding load" : "Passive mode (0 W HVAC)"}
            </span>
          </div>
        </div>
      </div>

      <div className="climate-layout" style={{ marginTop: "20px" }}>
        {/* Left Column: Steady-State Representative Snapshot */}
        <section className="climate-panel selection-panel">
          <div className="panel-heading">
            <div>
              <h2>Representative Hour Heat Breakdown</h2>
              <p>
                Peak outdoor temperature snapshot at {steady_state.representative_hour.slice(11, 16)} (T_out = {steady_state.t_out_c.toFixed(1)} °C, T_in = {steady_state.t_in_c.toFixed(1)} °C)
              </p>
            </div>
            <Activity aria-hidden className="text-slate-400" />
          </div>

          <div className="metrics-grid" style={{ gridTemplateColumns: "1fr 1fr" }}>
            <div className="climate-metric">
              <span>Wall Conduction (Q_walls)</span>
              <strong>{steady_state.q_cond_walls_w.toFixed(1)} W</strong>
            </div>
            <div className="climate-metric">
              <span>Roof Conduction (Q_roof)</span>
              <strong>{steady_state.q_cond_roof_w.toFixed(1)} W</strong>
            </div>
            <div className="climate-metric">
              <span>Window Conduction (Q_win)</span>
              <strong>{steady_state.q_cond_windows_w.toFixed(1)} W</strong>
            </div>
            <div className="climate-metric">
              <span>Solar Radiation (Q_solar)</span>
              <strong>{steady_state.q_solar_w.toFixed(1)} W</strong>
            </div>
            <div className="climate-metric">
              <span>Ventilation Load (Q_vent)</span>
              <strong>{steady_state.q_vent_w.toFixed(1)} W</strong>
            </div>
            <div className="climate-metric">
              <span>Occupant Sensible (Q_occ)</span>
              <strong>{steady_state.q_occ_w.toFixed(1)} W</strong>
            </div>
            <div className="climate-metric">
              <span>HVAC Holding Load (Q_hvac)</span>
              <strong style={{ color: steady_state.q_hvac_w !== 0 ? "#1b5e85" : "inherit" }}>
                {steady_state.q_hvac_w.toFixed(1)} W
              </strong>
            </div>
            <div className="climate-metric">
              <span>Net Heat Flow (Q_net)</span>
              <strong>{steady_state.q_net_w.toFixed(1)} W</strong>
            </div>
          </div>

          <div style={{ marginTop: "16px" }}>
            <button
              type="button"
              className="secondary-button"
              onClick={onNavigateToSimulation}
            >
              <ArrowLeft aria-hidden />
              <span>Back to Simulation Workspace</span>
            </button>
          </div>
        </section>

        {/* Right Column: Physical Assumptions & System Metadata */}
        <section className="climate-panel summary-panel">
          <div className="panel-heading">
            <div>
              <h2>Model Metadata &amp; Assumptions</h2>
              <p>Transparent engineering modeling boundaries defined by the server</p>
            </div>
            <Cpu aria-hidden className="text-slate-400" />
          </div>

          <div className="simulation-meta-card">
            <div className="meta-item">
              <span>Operational Mode</span>
              <strong style={{ textTransform: "uppercase" }}>{mode}</strong>
            </div>
            <div className="meta-item">
              <span>Total Thermal Capacitance</span>
              <strong>{(capacitance_j_per_k / 1000).toFixed(1)} kJ/K</strong>
            </div>
            <div className="meta-item">
              <span>Max Temp Overshoot</span>
              <strong>+{comfort.peak_deviation_above_k.toFixed(1)} K</strong>
            </div>
            <div className="meta-item">
              <span>Max Temp Undershoot</span>
              <strong>-{comfort.peak_deviation_below_k.toFixed(1)} K</strong>
            </div>
          </div>

          <div className="source-banner source-live" style={{ marginTop: "12px" }}>
            <Database aria-hidden />
            <div>
              <strong>Governing Physics Engine Assumptions</strong>
              <ul style={{ margin: "6px 0 0", paddingLeft: "16px", fontSize: "11px", color: "#577382", lineHeight: "1.5" }}>
                {simulationResult.assumptions.slice(0, 4).map((a, idx) => (
                  <li key={idx}>{a}</li>
                ))}
              </ul>
            </div>
          </div>

          <div className="orientation-disclaimer" style={{ marginTop: "12px" }}>
            <Info aria-hidden />
            <span>
              Detailed 24-hour time-series charts and optimization breakdown will be available in the upcoming Results Dashboard.
            </span>
          </div>
        </section>
      </div>
    </div>
  );
}
